title: Samantha Paul # your name (or website title) here
logo: "/images/FACE.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Military spouse and Data Analyst with a love of helping others and problem solving. 
  My strong communication and people skills enables me to act as a translator between technology and people. 
  These skills paired with my knowledge in technology of SQL, Excel and Tableau allows me to transform data into 
  impactful insights that lead to the best business decisions. 
  <br><br>
  <a href="https://www.linkedin.com/in/samantha-paul-1106b1246//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
